### ISSUE TITLE
Different lock screen and wallpaper. 

### ISSUE THREAD

**Issue by AjaySarwan** [redwarp/gif-wallpaper#81]
Hello
I love your application and have a request and did not know where to put it. Thus added here as an issue.
I would like an option for keeping a different gifs for wallpaper and lock screen.

Thank you.

**Comment by redwarp** [comment]
Hey! That is the perfect place to put an issue!

But as far as I am aware this is not possible: when I looked at how to code it, it seems it's only possible to choose a different one for "fixed Images". Live wallpapers don't seem to have such options.
It's a bit of a shame because this is an often requested request!
